record:
  repo_id: &repo_id "test/test"
  # Suggested format: <hf_username>/<description>, description = task.description -> Verb_SourceObject_prep_TargetObject
  # e.g. Pick up the green cube and put it into the trash bin -> pick_greencube_into_trashbin
  debug: 0 # if True, robot will not execute any actions, but gripper can still be controlled
  user_notes:  # any additional notes about the dataset
  fps: 15 # dataset and camera frame rate
  control_mode: &control_mode "oculus"  # teleoperation control mode (only "oculus" supported)
  use_gripper: &use_gripper true  # whether to use gripper
  run_mode: "run_record" # "run_record" or "run_policy" or "run_mix"

  # Robot type selection
  # Supported robots: dobot_dual_arm, franka_dual_arm, nero_dual_arm, arx_dual_arm, franka
  robot_type: &robot_type "franka"

  teleop:
    control_mode: *control_mode
    dual_arm: true  # dual-arm mode
    oculus_config:
      ip: "192.168.110.62"  # Oculus Quest IP address
      use_gripper: *use_gripper
      left_pose_scaler: [1.0, 1.0]   # left arm scaler
      left_channel_signs: [1, -1, 1, -1, 1, 1]  # left arm signs
      right_pose_scaler: [1.0, 1.0]  # right arm scaler
      right_channel_signs: [1, -1, 1, -1, 1, 1]  # right arm signs
      visualize_placo: false  # whether to visualize robot using placo
      
  robot:
    robot_ip: &ip "192.168.110.15" # dobot server ip
    robot_port: 4242  # dual-arm zerorpc port (single port for both arms)
    use_gripper: *use_gripper
    gripper_ip: "192.168.110.15" # gripper zerorpc ip, if different from robot_ip, set to robot_ip
    gripper_port: 4243  # gripper zerorpc port (single port for both arms)
    close_threshold: 0.7 # threshold to determine gripper open/close
    gripper_bin_threshold: 0.98 # threshold to determine gripper is closed
    gripper_reverse: false  # If gripper moves opposite, flip this value
    gripper_max_open: 0.085 # Robotiq 2F-85 max open width in meters

  policy:
    type: "act"  # 策略类型 (act, diffusion)
    device: "cuda"  # 运行设备 (cuda, cpu)
    push_to_hub: False  # 禁用模型推送
    pretrained_path: "/home/deepcybo/lerobot/franka_workspace/outputs/train/act_test9/checkpoints/last/pretrained_model"  # 预训练模型路径下要包括config.json

  task:
    description: "use the left hand to pick up the bottle and insert it into the blender then pressing the button" # task description
    num_episodes: 10 # number of episodes to record
    display: True # Whether to display the data during recording
    resume: false # whether to resume from an existing dataset
    resume_dataset: roboticiq/pick_all_yellow_cube_to_brown_basket_20260208_v01 # dataset to resume from if resume is True
  
  time:
    episode_time_sec: 6000 # max time per episode in seconds
    reset_time_sec: 6000 # max time to reset between episodes in seconds
    save_meta_period: 1 # Save metadata after every N episodes

  cameras:
    left_wrist_cam_serial: "317422075656"   # left wrist camera serial number
    right_wrist_cam_serial: "344322074412"  # right wrist camera serial number
    head_cam_serial: "243322071821"         # head (overhead) camera serial number
    width: 424 # 640 424
    height: 240 # 360 240

  storage:
    push_to_hub: False # whether to push the dataset to your huggingface repo after recording

replay:
  dataset_name: dual_dobot/milk_shake_3_15_step1_20260315_v08
  episode_idx: 0 # episode index to replay
  robot_type: *robot_type  # robot type to use for replay
  robot:
    ip: *ip
    robot_port: 4242  # dual-arm zerorpc port
  control_mode: *control_mode 

visualize:
  dataset_name: dual_dobot/milk_shake_3_15_step1_20260315_v08
  episode_index: 0 # episode index to visualize




